services:
  - type: web
    name: spare2
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m pip install --upgrade pip
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///app.db 